### ISSUE TITLE
hooks to make dplR integration easier

### ISSUE THREAD

**Issue by AndyBunn** [RonaldVisser/SGC#1]
Hi Ronald, for incorporation into `{dplR}` I suggest adding something like this into the functions as checks on arguments `x` and `overlap`:

```
  if(!("rwl" %in% class(x))) warning("'x' is not class rwl")
  if(any(length(overlap)!=1 | !is.numeric(overlap) | 
         overlap%%1!=0 | overlap < 1)){
    stop("'overlap' should be a single integer >0")
  }

```
Although I'm not sure what an appropriate value for `overlap` might be.

I'd advocate changing `GLK` to `glk` and `SGC` to `sgc` for to be consistent with `{dplR}`. I'm happy to make any of these changes on the `{dplR}` repo or they can happen here.

Thanks for working on this. -A

**Comment by RonaldVisser** [comment]
Thanks for the comments, Andy! 

I have included your suggestions and renamed the functions to lower case. I have also set the default `overlap` to 50 and included a warning if a lower overlap threshold is set.
In addition, I have added the functions `sgc_p()` and `glk_p()` that calculate the probability of exceedence of the respective functions.
All four functions updated/added now have documentation in the man-folder.

Please let me know if you need anything more.
